#
# Blog Settings
#
author: John Van Tuyl
description: Software Developer
url: https://jpvantuyl.github.io
title: John Van Tuyl
subtitle: Software Developer
gravatar_url: https://2.gravatar.com/avatar/9e8fedfcd92b20263ceaab4e6cec2202
subscribe_rss: https://jpvantuyl.github.io/atom.xml

# Github repositories
github_user: jpvantuyl
github_repo_url: https://github.com/jpvantuyl/jpvantuyl.github.io/

# Twitter
twitter_user: jpvantuyl
twitter_tweet_button: false

# Disqus Comments
#disqus_short_name: johnvantuyl
#disqus_show_comment_count: true

# Google Analytics
# google_analytics_tracking_id: UA-48718702-1


#
# Jekyll Settings
#
markdown: GFM
permalink: /posts/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories
exclude: [vendor]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
